### ISSUE TITLE
missing 2 events 

### ISSUE THREAD

**Issue by ilya-peysakhov** [Greco1899/scrape_ufc_stats#22]
these 2 are not in the stats file

UFC 294: Makhachev vs. Volkanovski 2
UFC Fight Night: Holloway vs. The Korean Zombie

**Comment by Greco1899** [comment]
Hi @ilya-peysakhov.

Thanks for raising this. The mentioned events were scrapped and added to ufc_event_details.csv but the other data like fight details, stats, etc., were not uploaded at the time to the official site.

In subsequent refreshes, the scripts check if the events are added to ufc_event_details.csv before scraping their respective stats. And since the events are 'present' in the file, the stats were not retroactively added.

What you can do is to run [scrape_ufc_stats_all_historical_data.ipynb](https://github.com/Greco1899/scrape_ufc_stats/blob/main/scrape_ufc_stats_all_historical_data.ipynb) to get your own dataset.

**Comment by ilya-peysakhov** [comment]
Thanks!
